project:
  type: website

website:
  title: "Sunmin Hong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sunmin.cv.pdf
        text: Curriculum Vitae
      - href: assignment1.qmd
        text: assignmnet1
      - href: assignment2.qmd
        text: assignmnet2
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual






