project:
  type: website

website:
  title: "Sunmin Hong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sunmin.cv.pdf
        text: Curriculum Vitae
      - href: assignmnet.1.qmd
        text: assignmnet.1
      - href: assignmnet.2.qmd
        text: assignmnet.2  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

